### PR TITLE
Connectable class is no longer abstract

### PR DESCRIPTION
**Pull request by jeppes**
Trying to make `ConnectableClass` into an abstract class has not worked out well in practice. Most subclasses simply just leave `onDispose` blank. 

@JensAyton

### CODE REVIEW

**Comment by JensAyton** [comment]
This one has failing tests, not flakiness

**Comment by JensAyton** [comment]
Otherwise good

**Comment by jeppes** [comment]
Right. 🤦

**Comment by jeppes** [comment]
Xcode's error color really doesn't play well with my color blindness 🙃

**Comment by jeppes** [comment]
Fixed, @JensAyton

**Pull request merged**
